# Generated by Django 3.0.2 on 2020-02-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_auto_20200214_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
