# Generated by Django 3.0.2 on 2020-02-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_subject_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='lecture_hours',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='practical_assessment_total',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='practical_duration_hours',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='practical_hours',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='theory_assessment_total',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='theory_duration_hours',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='tutorial_hours',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
