# Generated by Django 3.0.2 on 2020-02-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_subject_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
